"""Primitives shared across the domain model."""
from __future__ import annotations

import re
from enum import Enum

from pydantic import BaseModel, Field, field_validator

_HEX_RE = re.compile(r"^#?([0-9a-fA-F]{6})$")


class RGB(BaseModel):
    """A free-form 24-bit colour.

    The application stores whatever colour the user picks. Vendor palettes are a
    *export-time* concern -- see `djprep.export.color`. Keeping colour free here
    is what lets the same preparation target Rekordbox (16-colour palette),
    Serato (different palette) or a plain JSON export without re-editing.
    """

    r: int = Field(ge=0, le=255)
    g: int = Field(ge=0, le=255)
    b: int = Field(ge=0, le=255)

    @classmethod
    def from_hex(cls, value: str) -> RGB:
        m = _HEX_RE.match(value.strip())
        if not m:
            raise ValueError(f"invalid hex colour: {value!r}")
        h = m.group(1)
        return cls(r=int(h[0:2], 16), g=int(h[2:4], 16), b=int(h[4:6], 16))

    def to_hex(self) -> str:
        return f"#{self.r:02X}{self.g:02X}{self.b:02X}"

    def __str__(self) -> str:  # pragma: no cover - debug convenience
        return self.to_hex()


class Source(str, Enum):
    """Provenance of a cue or loop. Drives the human-in-the-loop feedback log."""

    AI = "ai"           # generated by the recommendation engine, untouched
    AI_EDITED = "ai_edited"  # generated by AI, then moved/renamed/recoloured by the user
    USER = "user"       # created by hand


class Reason(BaseModel):
    """One piece of evidence behind a recommendation.

    Every recommendation must be explainable as a list of these. `code` is stable
    and machine-readable (used for evaluation + model refitting); `text` is the
    human string shown in the UI; `weight` is this reason's signed contribution
    to the confidence logit, so the UI can sort reasons by how much they mattered.
    """

    code: str
    text: str
    weight: float = 0.0
    value: float | None = None  # the raw measured quantity, for debugging/eval

    @field_validator("code")
    @classmethod
    def _snake(cls, v: str) -> str:
        if not re.match(r"^[a-z0-9_]+$", v):
            raise ValueError("reason codes must be lower_snake_case")
        return v
